import { GoogleGenerativeAI } from "@google/generative-ai";
import { RepoData } from "./github";

const apiKey = process.env.GOOGLE_GENERATIVE_AI_API_KEY;

if (!apiKey) {
  console.warn("GOOGLE_GENERATIVE_AI_API_KEY is not set in environment variables");
}

const genAI = new GoogleGenerativeAI(apiKey || "");

export async function generateReadme(repoData: RepoData): Promise<string> {
  if (!apiKey) {
    throw new Error("Gemini API key is not configured.");
  }

  const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

  const systemPrompt = `You are an Expert Technical Writer and Developer. Your task is to generate a comprehensive, professional, and visually appealing README.md file for a GitHub repository.

Here is the data gathered from the repository:
- Owner: ${repoData.owner}
- Repository Name: ${repoData.repo}
- Root Directory Structure: 
${repoData.tree.join("\n")}

Here are the contents of critical files found in the repository:
${repoData.files.map(file => `\n--- START OF ${file.name} ---\n${file.content}\n--- END OF ${file.name} ---\n`).join("\n")}

Based on this information, please generate a complete README.md following these requirements:
1. **Project Title & Description**: Create a clear, engaging title and a concise description of what the project does.
2. **Tech Stack**: Identify the technologies used based on the files provided (e.g., package.json, requirements.txt, entry files) and display them using Shields.io style badges if possible (e.g., \`![React](https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB)\`).
3. **Key Features**: List the main features of the project based on your analysis of the code.
4. **Installation**: Provide step-by-step installation instructions.
5. **Usage**: Explain how to run or use the project.
6. **Project Structure**: Include a brief section explaining the root directory structure.
7. **Badge**: At the very bottom of the README, you must include this exact text on its own line: \`<br/><br/>_Generated by [Auto-README](https://github.com/)_\`

Output ONLY the markdown content. Do not wrap the entire output in a markdown code block (\`\`\`markdown ... \`\`\`), just output the raw markdown text directly. Ensure the tone is professional, welcoming, and developer-friendly.`;

  try {
    const result = await model.generateContent(systemPrompt);
    const response = await result.response;
    let text = response.text();
    
    // Clean up if the model wrapped it in ```markdown
    if (text.startsWith("\`\`\`markdown")) {
      text = text.replace(/^\`\`\`markdown\n/, "").replace(/\n\`\`\`$/, "");
    }
    
    return text;
  } catch (error: any) {
    console.error("Error calling Gemini API:", error);
    throw new Error("Failed to generate README using AI.");
  }
}
