import { GoogleGenerativeAI } from "@google/generative-ai";
import OpenAI from "openai";
import { RepoData } from "./github";

const apiKey = process.env.GOOGLE_GENERATIVE_AI_API_KEY;
const openRouterApiKey = process.env.OPENROUTER_API_KEY;

if (!apiKey) {
  console.warn("GOOGLE_GENERATIVE_AI_API_KEY is not set in environment variables");
}
if (!openRouterApiKey) {
  console.warn("OPENROUTER_API_KEY is not set in environment variables");
}

const genAI = new GoogleGenerativeAI(apiKey || "");
const openai = new OpenAI({
  baseURL: "https://openrouter.ai/api/v1",
  apiKey: openRouterApiKey || "",
});

export async function generateReadme(repoData: RepoData): Promise<string> {
  if (!apiKey && !openRouterApiKey) {
    throw new Error("No AI API keys are configured.");
  }

  const generationConfig = { temperature: 0.3 };
  const proModel = genAI.getGenerativeModel({ model: "gemini-2.5-pro", generationConfig });
  const flashModel = genAI.getGenerativeModel({ model: "gemini-2.5-flash", generationConfig });

  const systemPrompt = `You are a Senior Software Engineer acting as an Expert Technical Writer. Your task is to generate a comprehensive, professional, and visually appealing README.md file for a top-tier open-source GitHub repository.

Here is the data gathered from the repository:
- Owner: ${repoData.owner}
- Repository Name: ${repoData.repo}
- Root Directory Structure: 
${repoData.tree.join("\n")}

Here are the contents of critical files found in the repository:
${repoData.files.map(file => `\n--- START OF ${file.name} ---\n${file.content}\n--- END OF ${file.name} ---\n`).join("\n")}

Based on this information, generate a complete README.md strictly enforcing this structure:

1. **Title & Badges**: The Project Title followed by dynamic Shields.io badges for the languages and frameworks identified (e.g., \`![React](https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB)\`).
2. **Overview**: A high-level, professional summary of what the project does.
3. **System Architecture**: A bulleted breakdown of how the core files and modules interact.
4. **Prerequisites**: What needs to be installed first before running the project.
5. **Installation**: Exact CLI commands (e.g., \`npm install\`, \`pip install\`, etc.) formatted inside markdown code blocks.
6. **Usage**: Examples of how to run or use the project, including CLI run commands if applicable.
7. **Footer**: At the very bottom, you MUST include this exact text on its own line: \`<br/><br/>_Generated by [Auto-README](https://auto-readme-livid.vercel.app/)_\`

Output ONLY the markdown content. Do not wrap the output in a markdown code block (\`\`\`markdown ... \`\`\`). Keep the tone highly analytical, factual, and strictly professional without creative hallucinations.`;

  const processResponse = (text: string) => {
    if (text.startsWith("\`\`\`markdown")) {
      return text.replace(/^\`\`\`markdown\n/, "").replace(/\n\`\`\`$/, "");
    }
    return text;
  };

  async function fallbackToOpenRouter(): Promise<string> {
    console.warn(`[AI] Triggering Ultimate Fallback: OpenRouter (meta-llama/llama-3.3-70b-instruct:free)...`);
    if (!openRouterApiKey) {
      throw new Error("Failed to generate README: Gemini failed and OpenRouter API key is missing.");
    }

    try {
      const response = await openai.chat.completions.create({
        model: "meta-llama/llama-3.3-70b-instruct:free",
        messages: [{ role: "system", content: systemPrompt }],
        temperature: 0.3,
      });

      const text = response.choices[0]?.message?.content || "";
      return processResponse(text);
    } catch (openRouterError: unknown) {
      const errorMsg = openRouterError instanceof Error ? openRouterError.message : String(openRouterError);
      console.error("[AI] OpenRouter Fallback completely failed:", errorMsg);
      throw new Error("All AI providers failed to generate README.");
    }
  }

  // Attempt 1: Gemini 2.5 Pro
  try {
    console.log("[AI] Layer 1: Attempting generation with gemini-2.5-pro...");
    const result = await proModel.generateContent(systemPrompt);
    const response = await result.response;
    return processResponse(response.text());
  } catch (error: unknown) {
    const errorMsg = error instanceof Error ? error.message : String(error);

    // Attempt 2: Gemini 2.5 Flash on rate limits
    if (errorMsg.includes("503") || errorMsg.includes("429") || errorMsg.includes("quota") || errorMsg.includes("unavailable")) {
      console.warn(`[AI] Layer 1 failed (gemini-2.5-pro rate-limited). Error: ${errorMsg}`);
      console.warn(`[AI] Layer 2: Falling back to gemini-2.5-flash...`);

      try {
        const fallbackResult = await flashModel.generateContent(systemPrompt);
        const fallbackResponse = await fallbackResult.response;
        return processResponse(fallbackResponse.text());
      } catch (fallbackError: unknown) {
        const fallbackErrorMsg = fallbackError instanceof Error ? fallbackError.message : String(fallbackError);
        console.error("[AI] Layer 2 failed (Gemini Flash error):", fallbackErrorMsg);
        // Attempt 3: OpenRouter
        return await fallbackToOpenRouter();
      }
    } else {
      console.warn(`[AI] Layer 1 completely failed with unknown error: ${errorMsg}`);
      // Attempt 3: OpenRouter
      return await fallbackToOpenRouter();
    }
  }
}
